Controllers/CategoriaController.cs
using System.Linq;
using Auth.Data;
using Auth.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Auth.Controllers;

[Authorize(Roles = "admin")]
public class CategoriaController : Controller
{
    private readonly AppDbContext _db;
    public CategoriaController(AppDbContext db)
    {
        _db = db;
    }

    [AllowAnonymous]
    public IActionResult Index()
    {
        var categorias = _db.Categorias.AsNoTracking().OrderBy(x => x.Nome).ToList();
        return View(categorias);
    }

    [HttpGet]
    public IActionResult Cadastrar()
    {
        var categoria = new CategoriaModel();
        return View(categoria);
    }

    [HttpPost]
    public IActionResult Cadastrar(CategoriaModel categoria)
    {
        if (!ModelState.IsValid)
        {
            return View(categoria);
        }
        _db.Categorias.Add(categoria);
        _db.SaveChanges();
        return RedirectToAction("Index");


    }

    [HttpGet]
    public IActionResult Alterar(int id)
    {
        var categoria = _db.Categorias.Find(id);
        if (categoria is null)
        {
            return RedirectToAction("Index");
        }
        return View(categoria);
    }

    [HttpPost]
    public IActionResult Alterar(int id, CategoriaModel categoria)
    {
        var categoriaOriginal = _db.Categorias.Find(id);
        if (categoriaOriginal is null)
        {
            return RedirectToAction("Index");
        }

        if (!ModelState.IsValid)
        {
            return View(categoria);
        }
        categoriaOriginal.Nome = categoria.Nome;
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Excluir(int id)
    {
        var categoria = _db.Categorias.Find(id);
        if (categoria is null)
        {
            return RedirectToAction("Index");
        }
        return View(categoria);
    }

    [HttpPost]
    public IActionResult ProcessarExclusao(int id)
    {
        var categoriaOriginal = _db.Categorias.Find(id);
        if (categoriaOriginal is null)
        {
            return RedirectToAction("Index");
        }

        _db.Categorias.Remove(categoriaOriginal);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

}

Controllers/FornecedorController.cs
using Auth.Data;
using Auth.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;

namespace Auth.Controllers;

[Authorize(Roles = "admin")]
public class FornecedorController : Controller
{
    private readonly AppDbContext _db;
    private readonly IWebHostEnvironment _env;

    public FornecedorController(AppDbContext db, IWebHostEnvironment env)
    {
        _db = db;
        _env = env;
    }


    private void CarregarCategorias2(int? idCategoria = null)
    {
        var categorias2 = _db.Categorias.OrderBy(c => c.Nome).ToList();
        ViewBag.Categorias2 = categorias2;
    }

    [AllowAnonymous]
    public IActionResult Index()
    {
        var fornecedores = _db.Fornecedores
            .Include(p => p.Categoria)
            .AsNoTracking()
            .OrderBy(p => p.Nome)
            .ToList();
        CarregarCategorias2();
        return View(fornecedores);
    }

    private void CarregarCategorias(int? idCategoria = null)
    {
        var categorias = _db.Categorias.OrderBy(c => c.Nome).ToList();
        var categoriasSelectList = new SelectList(
            categorias, "Id", "Nome", idCategoria);
        ViewBag.Categorias = categoriasSelectList;
    }


    [HttpGet]
    public IActionResult Cadastrar()
    {
        CarregarCategorias();
        var fornecedor = new FornecedorModel();
        return View(fornecedor);
    }

    [HttpPost]
    public IActionResult Cadastrar(FornecedorModel fornecedor)
    {
        if (!ModelState.IsValid)
        {
            CarregarCategorias(fornecedor.IdCategoria);
            return View(fornecedor);
        }
        _db.Fornecedores.Add(fornecedor);
        if (_db.SaveChanges() > 0)
        {
            var caminhoImagem = $"{_env.WebRootPath}//img//fornecedor//{fornecedor.Id.ToString("D6")}.jpg";
            SalvarUploadImagemAsync(caminhoImagem, fornecedor.ArquivoImagem).Wait();
        }
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Alterar(int id)
    {
        var fornecedor = _db.Fornecedores.Find(id);
        if (fornecedor is null)
        {
            return RedirectToAction("Index");
        }
        CarregarCategorias(fornecedor.IdCategoria);
        return View(fornecedor);
    }

    
    [HttpPost]
    public IActionResult Alterar(int id, FornecedorModel fornecedor)
    {
        var fornecedorOriginal = _db.Fornecedores.Find(id);
        if (fornecedorOriginal is null)
        {
            return RedirectToAction("Index");
        }

        CarregarCategorias(fornecedor.IdCategoria);
        fornecedorOriginal.Nome = fornecedor.Nome;
        fornecedorOriginal.Email = fornecedor.Email;
        fornecedorOriginal.Telefone = fornecedor.Telefone;
        fornecedorOriginal.IdCategoria = fornecedor.IdCategoria;
        fornecedorOriginal.Cidade = fornecedor.Cidade;
        fornecedorOriginal.UF = fornecedor.UF;
        fornecedorOriginal.aPartir = fornecedor.aPartir;
        fornecedorOriginal.ValorPessoa = fornecedor.ValorPessoa;
        fornecedorOriginal.Caracteristicas = fornecedor.Caracteristicas;
        fornecedorOriginal.IsPremium = fornecedor.IsPremium;
        _db.SaveChanges();
        if (fornecedor.ArquivoImagem is not null)
        {
            var caminhoImagem = $"{_env.WebRootPath}//img//fornecedor//{fornecedor.Id.ToString("D6")}.jpg";
            SalvarUploadImagemAsync(caminhoImagem, fornecedor.ArquivoImagem).Wait();
        }

        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Excluir(int id)
    {
        var fornecedor = _db.Fornecedores.Find(id);
        if (fornecedor is null)
        {
            return RedirectToAction("Index");
        }
        return View(fornecedor);
    }

    [HttpPost]
    public IActionResult ProcessarExclusao(int id)
    {
        var fornecedorOriginal = _db.Fornecedores.Find(id);
        if (fornecedorOriginal is null)
        {
            return RedirectToAction("Index");
        }
        _db.Fornecedores.Remove(fornecedorOriginal);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public async Task<bool> SalvarUploadImagemAsync(
       string caminhoArquivoImagem, IFormFile imagem,
       bool salvarQuadrada = true)
    {
        if (imagem is null)
        {
            return false;
        }
        var ms = new MemoryStream();
        await imagem.CopyToAsync(ms);
        ms.Position = 0;
        var img = await Image.LoadAsync(ms);

        if (salvarQuadrada)
        {
            var tamanho = img.Size();
            var ladoMenor = (tamanho.Height < tamanho.Width) ? tamanho.Height : tamanho.Width;
            img.Mutate(i =>
                i.Resize(new ResizeOptions()
                {
                    Size = new Size(ladoMenor, ladoMenor),
                    Mode = ResizeMode.Crop
                })
            );
        }

        await img.SaveAsJpegAsync(caminhoArquivoImagem);
        return true;
    }
}

Controllers/OrcamentoController.cs
using Auth.Data;
using Auth.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;

namespace Auth.Controllers;


[Authorize(Roles = "admin")]

public class OrcamentoController : Controller
{
    private readonly AppDbContext _db;
    private readonly IWebHostEnvironment _env;

    public OrcamentoController(AppDbContext db, IWebHostEnvironment env)
    {
        _db = db;
        _env = env;
    }

    [AllowAnonymous]
    public IActionResult Index()
    {
        var orcamentos = _db.Orcamentos
            .AsNoTracking()
            .ToList();
        return View(orcamentos);
    }

    [AllowAnonymous]
    public IActionResult Mostrar(int idOrcamento)
    {
        idOrcamento = 1;
        var orcamentos = _db.Orcamentos
            .AsNoTracking()
            .ToList()
            .LastOrDefault(p => p.Id == idOrcamento);

        return View(orcamentos);
    }

    private void CarregarFornecedores(int? idFornecedor = null)
    {
        var fornecedores = _db.Fornecedores.OrderBy(c => c.Nome).ToList();
        ViewBag.Fornecedores = fornecedores;
    }

    private void CarregarCategorias(int? idCategoria = null)
    {
        var categorias = _db.Categorias.OrderBy(c => c.Nome).ToList();
        ViewBag.Categorias = categorias;
    }

    [AllowAnonymous]
    [HttpGet]
    public IActionResult Cadastrar(int id)
    {
        var usuario = _db.Usuarios.Find(id);
        CarregarFornecedores();
        CarregarCategorias();
        var orcamento = new OrcamentoModel();
        return View(orcamento);
    }

    [AllowAnonymous]
    [HttpPost]
    public IActionResult Cadastrar(int id, int[] fornecedores, OrcamentoModel orcamento)
    {
    
        if (!ModelState.IsValid)
        {
            
            return View(orcamento);
        }

        for (int i=0; i<fornecedores.Length; i++)
        {
            var fornecedor = _db.Fornecedores.Find(fornecedores[i]);
            orcamento.ValorOrcamento = orcamento.ValorOrcamento + fornecedor.aPartir;   
        }
        orcamento.Id = 1;
        _db.Orcamentos.Update(orcamento);
        _db.SaveChanges();
        return RedirectToAction("Mostrar", new { idOrcamento = orcamento.Id });
    }
}

Controllers/UsuarioController.cs
using System.Linq;
using Auth.Data;
using Auth.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
namespace Auth.Controllers;
using static BCrypt.Net.BCrypt;

[Authorize(Roles = "admin")]
public class UsuarioController : Controller
{
    private readonly AppDbContext _db;

    public UsuarioController(AppDbContext db)
    {
        _db = db;
    }


    public IActionResult Index()
    {

        var usuarios = _db.Usuarios.AsNoTracking().OrderBy(x => x.Nome).ToList();
        return View(usuarios);
    }

    [HttpGet]
    public IActionResult Cadastrar()
    {
        var usuario = new UsuarioModel();
        return View(usuario);
    }

    [HttpPost]
    public async Task<IActionResult> Cadastrar(UsuarioModel usuario)
    {
        if (!ModelState.IsValid)
        {
            return View(usuario);
        }

        var existente = _db.Usuarios.Any(u => u.Email == usuario.Email);
        if (existente)
        {
            ModelState.AddModelError("Email", "Já existe um usuário cadastrado com este e-mail.");
            return View(usuario);
        }

        usuario.Senha = HashPassword(usuario.Senha, 10);
        await _db.Usuarios.AddAsync(usuario);
        if (_db.SaveChanges() > 0)
        {
            return RedirectToAction(nameof(Index));
        }
        else
        {
            ModelState.AddModelError(string.Empty,
                "Ocorreu um erro desconhecido ao cadastrar seus dados. Tente novamente mais tarde.");
            return View(usuario);
        }
    }

    [HttpGet]
    public IActionResult Alterar(int id)
    {

        var usuario = _db.Usuarios.Find(id);
        if (usuario is null)
        {
            return RedirectToAction("Index");
        }
        return View(usuario);
    }

    [HttpPost]
    public IActionResult Alterar(int id, UsuarioModel usuario)
    {
        var usuarioOriginal = _db.Usuarios.Find(id);
        if (usuarioOriginal is null)
        {
            return RedirectToAction("Index");
        }

        usuarioOriginal.Nome = usuario.Nome;
        usuarioOriginal.Email = usuario.Email;
        usuarioOriginal.IsAdmin = usuario.IsAdmin;
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Excluir(int id)
    {
        var usuarios = _db.Usuarios.Find(id);
        if (usuarios is null)
        {
            return RedirectToAction("Index");
        }
        if (User.Identity.Name.ToString() != (usuarios.Nome))
        {
            return View(usuarios);
        }
        return View("Alert");
    }

    [HttpPost]
    public IActionResult ProcessarExclusao(int idUsuario)
    {
        var usuarioOriginal = _db.Usuarios.Find(idUsuario);
        if (usuarioOriginal is null)
        {
            return RedirectToAction("Index");
        }

        _db.Usuarios.Remove(usuarioOriginal);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }


    [HttpGet]
    public IActionResult AlterarSenha(int id)
    {

        var usuario = _db.Usuarios.Find(id);
        if (usuario is null)
        {
            return RedirectToAction("Index");
        }
        return View(usuario);
    }

    [HttpPost]
    public IActionResult AlterarSenha(int id, UsuarioModel usuario, string senhaAntiga)
    {
        var usuarioOriginal = _db.Usuarios.Find(id);

        if (usuarioOriginal is null)
        {
            return RedirectToAction("Index");
        }
        if (HashPassword(senhaAntiga) == usuarioOriginal.Senha)
        {
            ModelState.AddModelError("Senha", "A senha está incorreta.");
            return View("AlterarSenha");
        }
        else
        {
            usuarioOriginal.Senha = HashPassword(usuario.Senha);
        }
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;


<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/estilos.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" defer></script>
    <link rel="stylesheet" href="/lib/lightbox2/dist/css/lightbox.min.css">
    <script src="/lib/lightbox2/dist/js/lightbox-plus-jquery.min.js" defer></script>
    <script src="https://kit.fontawesome.com/95a02bd20d.js" defer></script>
    <title>DescompliCase</title>
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-light bg-light bg-opacity-25 border-bottom border-danger border-3 border-opacity-10">
        <div class="container">
            <a class="navbar-brand" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Icon-only" asp-controller="Home" asp-action="Index"><i class="bi-heart text-danger mx-1"></i>DESCOMPLI<span class="text-danger">CASE</span></a>
            <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse" data-bs-target="#navMenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end align-items-center text-center" id="navMenu">
                <ul class="navbar-nav mt-lg-0">

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item my-3">
                            <a class="nav-link text-info border border-1 border-info border-opacity-50 me-1" asp-controller="Categoria" asp-action="Index">Categorias</a>
                        </li>
                        <li class="nav-item  my-3">
                            <a class="nav-link text-info border border-1 border-info border-opacity-50 me-1" asp-controller="Fornecedor" asp-action="Index">Fornecedores</a>
                        </li>
                        <li class="nav-item  my-3">
                            <a class="nav-link text-info border border-1 border-info border-opacity-50" asp-controller="Orcamento" asp-action="Index">Orçamento</a>
                        </li>

                        @if (User.IsInRole("admin"))
                        {
                            <a asp-controller="Usuario" asp-action="Index" class="nav-link link-dark my-1" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Home">
                            <i class="bi-house-gear h2 text-warning"></i>
                        </a>
                        }

                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle link-dark my-1 text-primary" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi-person-circle h2 text-primary"></i></a>
                            <ul class="dropdown-menu">
                                <p class="dropdown-header text-info"><b>@User.Identity.Name</b></p>
                                <li>
                                    <a asp-action="Alterar" asp-controller="Usuario" class="dropdown-item">Perfil</a>
                                </li>
                                <li>
                                    <a asp-controller="Usuario" asp-action="AlterarSenha" class="dropdown-item">Alterar Senha</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-controller="Home" asp-action="Logout">Sair</a>
                                </li>
                            </ul>
                        </div>
                        <a asp-controller="Home" asp-action="Index" class="nav-link link-dark my-1" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Home">
                            <i class="bi-house h2 text-danger opacity-10"></i>
                        </a>

                    }
                    else
                    {
                        <li class="nav-item mx-2 my-2">
                            <button class="btn btn-info rounded-5 opacity-50 px-3 py-1 shadow"><a class="nav-link link-light" asp-controller="Home" asp-action="Cadastrar"><b>Cadastre-se</b></a></button>
                        </li>
                        <li class="nav-item mx-2 my-2">
                            <button class="btn btn-outline-info rounded-5 px-4 py-1 shadow"><a class="nav-link link-info" asp-controller="Home" asp-action="Login">Entrar</a></button>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <main>
        @RenderBody()
    </main>

    <div class="col-12" style="height: 80vh;"></div>

    <footer class="col-12 text-center bg-danger bg-opacity-75 p-2">
        <div class="container mt-4">
            <p class="text-light">
                Copyright DescompliCase &copy; @DateTime.Now.Year<br>
                Todos os direitos reservados</p>
        </div>
    </footer>
</body>


</html>